[workspace]
members = ["mlem", "cmlem", "bindings"]

[package]
name = "petalo"
version = "0.1.0"
authors = ["Jacek Generowicz <jacg@my-post-office.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
structopt = "0.3"
ndarray = { version = "0.14", features = ["rayon"] }
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
nalgebra = "0.29"
ncollide3d = "0.32"
kiss3d = "0.31"
num-traits = "0.2"
hdf5 = "0.7.1"
uom = "0.31"
ordered-float = "2.2"
cmlem = { path = "cmlem" }
indicatif = "0.16.2"
itertools = "0.10.1"
binwrite = "0.2.1"
binrw = "0.4.0"
linfa = "0.4.0"
linfa-clustering = "0.4.0"


[dev-dependencies]
rstest = "0.6.4"
pretty_assertions = "0.6.1"
assert_approx_eq = "1.1"
proptest = "1.0.0"
tempfile = "3.2"
rand_isaac = "0.3.0"
ndarray-rand = "0.14.0"
rand_core = "0.6.3"
approx = "0.5.0"

[build-dependencies]
bindgen = "0.57"

[features]
compile-error = []
serial = []
ccmlem = []
