[package]
name = "petalo"
version = "0.1.0"
authors = ["Jacek Generowicz <jacg@my-post-office.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.21"
ncollide2d = "0.25"
ncollide3d = "0.25"
assert_approx_eq = "1.1"

[dev-dependencies]
rstest = "0.6.4"
pretty_assertions = "0.6.1"
proptest = "0.10.1"