[workspace]
members = ["cffi"]

[package]
name = "petalo"
version = "0.1.0"
authors = ["Jacek Generowicz <jacg@my-post-office.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
ndarray = { version = "0.13", features = ["rayon"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
nalgebra = "0.22"
ncollide3d = "0.25"
kiss3d = "0.26"
plotters = "0.3.0"
num-traits = "0.2"

[dev-dependencies]
rstest = "0.6.4"
pretty_assertions = "0.6.1"
assert_approx_eq = "1.1"
proptest = "0.10.1"
