[workspace]
members = ["mlem", "cmlem"]

[package]
name = "petalo"
version = "0.1.0"
authors = ["Jacek Generowicz <jacg@my-post-office.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
structopt = "0.3"
ndarray = { version = "0.14", features = ["rayon"] }
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
nalgebra = "0.24"
ncollide3d = "0.27"
kiss3d = "0.29"
num-traits = "0.2"
hdf5 = "0.7.1"
uom = "0.31"
cmlem = { path = "cmlem" }

[dev-dependencies]
rstest = "0.6.4"
pretty_assertions = "0.6.1"
assert_approx_eq = "1.1"
proptest = "1.0.0"
tempfile = "3.2"

[build-dependencies]
bindgen = "0.57"

[features]
compile-error = []
serial = []
