# TODO move me to a test data directory

# event_range
# sensitivity_image
# num_threads # this one should stay on the CLI
# ecut
# qcut

[input]
file    = "data/some-lors.h5"
dataset = "reco_info/lors"


[iterations]
number  = 4
subsets = 20


[fov]
nvoxels = [  10    ,   20    , 30    ]
size    = ["100 mm", "200 mm", "3 cm"]


[tof]
sigma = "200 ps"
cutoff = 3


[scatter]

phi.bins = 30

r.bins = 31
r.max  = "32 mm"

dz.bins = 33
dz.max  = "34 mm"

dt.bins = 35
dt.max = "36 ps"

z.bins = 37
z.length = "38 cm"
