# TODO move me to a test data directory

# event_range
# sensitivity_image
# num_threads # this one should stay on the CLI
# ecut
# qcut

iterations = 4
subsets = 20

tof = "200 ps"
# cutoff

nvoxels = [10, 20, 30]
fov_size = ["100 mm", "200 mm", "3 cm"]


[input]
file    = "data/some-lors.h5"
dataset = "reco_info/lors"


[scatter]

phi.bins = 30

r.bins = 31
r.max  = "32 mm"

dz.bins = 33
dz.max  = "34 mm"

dt.bins = 35
dt.max = "36 ps"

z.bins = 37
z.length = "38 cm"
