# TODO move me to a test data directory

# input_file
# dataset
# event_range
# sensitivity_image
# num_threads # this one should stay on the CLI
# ecut
# qcut

iterations = 4
subsets = 20

tof = "200 ps"
# cutoff

nvoxels = [10, 20, 30]
fov_size = ["100 mm", "200 mm", "3 cm"]

# scatter.phi.bins
# scatter.  z.bins
# scatter. dz.bins
# scatter.  r.bins
# scatter. dt.bins
#
# scatter. z.length
# scatter. r.max
# scatter.dt.max
# scatter.dz.max
