# TODO move me to a test data directory

# input_file
# dataset
# event_range
# sensitivity_image
# num_threads # this one should stay on the CLI
# ecut
# qcut

iterations = 4
subsets = 20

tof = "200 ps"
# cutoff

nvoxels = [10, 20, 30]
fov_size = ["100 mm", "200 mm", "3 cm"]



[scatter]

phi.bins = 30

# r.bins = 30
# r.max  = "30 mm"

# z.bins = 30
# z.length = "1 m"

# dz.bins = 30
# dz.max  = "215 mm"

# dt.bins = 30
# dt.max = "500 ps"
