[package]
name = "geometry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = "0.32.0"

[dev-dependencies]
pretty_assertions = "1.0"
float_eq = "0.7.0"
rstest = "0.12"
