[package]
name = "geometry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
units = { path = "../units" }
ncollide3d = "0.32"

[dev-dependencies]
pretty_assertions = "1.2.1"
rstest = "0.13"
