name: Build and Test
on:
  pull_request:
  push:
jobs:

  build-and-test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, macos-11]
        py: [38, 39]
        allow-fail: [false]
        include:
          - os: ubuntu-latest
            py: 310
            allow-fail: true
          - os: macos-10.15
            py: 310
            allow-fail: true
          - os: macos-11
            py: 310
            allow-fail: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - uses: Swatinem/rust-cache@v1

      - name: Install dependencies with Nix
        run: nix-shell --argstr py ${{ matrix.py }}

      - name: Test Pure Rust
        run: nix-shell --argstr py ${{ matrix.py }} --run "just test-rust-pure   --color=always"

      - name: Test Rust/C
        run: nix-shell --argstr py ${{ matrix.py }} --run "just test-rust-c      --color=always"

      - name: Test Pure Python
        run: nix-shell --argstr py ${{ matrix.py }} --run "just test-python-pure  --color=yes"

      - name: Compile PyO3
        run: nix-shell --argstr py ${{ matrix.py }} --run "just python-build-bindings"
        if: runner.os == 'Linux'

      - name: Test PyO3
        run: nix-shell --argstr py ${{ matrix.py }} --run "just test-python-bindings --color=yes"
        if: runner.os == 'Linux'

      - name: Test Julia
        run: nix-shell --argstr py ${{ matrix.py }} --run "just test-julia           --color=yes"
        if: runner.os == 'Linux'
