name: Build and Test
on:
  pull_request:
  push:
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
        py: [38]
        allow-fail: [false]
        include:
          - os: ubuntu-latest
            py: 39
            allow-fail: true
          - os: macos-10.15
            py: 39
            allow-fail: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: Swatinem/rust-cache@v1
      - run: nix-shell --argstr py ${{ matrix.py }}
      - run: nix-shell --argstr py ${{ matrix.py }} --run "cargo test"
      - run: nix-shell --argstr py ${{ matrix.py }} --run "cargo test -p cmlem"



# To debug interactively via tmate, add the following step to the steps above,
# at the point where you want the action to stop and give you control:

      # # Probably best to run this on only one matrix entry
      # # In tmate: `nix-shell -I nixpkgs=channel:nixos-unstable`
      # - name: Debug interactively
      #   uses: csexton/debugger-action@master

# When it reaches this point, the action log will show something like
#
#   ssh fV3pb4MynAFQKFFsWG4W5cSVp@nyc1.tmate.io
#
# + Copy-paste this into a terminal
# + press `q`
# + type `touch /tmp/keepalive`
# + type `nix-shell -I nixpkgs=channel:nixos-unstable`
#
# This will leave you in the build/deveopment environment of your project.
