name: Build and Test
on:
  pull_request:
  push:
jobs:
  testing123:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: Swatinem/rust-cache@v1
      - run: nix-shell
      - run: nix-shell --run "cargo test"
