name: "Test"
on:
  pull_request:
  push:
jobs:
  testing123:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: cachix/install-nix-action@v11
      - run: ls -alh
